default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: rails
  password: rails

development:
  <<: *default
  database: wallet_system_development

test:
  <<: *default
  database: wallet_system_test

production:
  <<: *default
  url: <%= ENV["DB_URL"] %>
